### PR TITLE
Added profiling and the generation of a flame graph OHM-100

### PR DESCRIPTION
**Pull request by rcrichton**
@devcritter could you review this for me?

### CODE REVIEW

**Comment by hnnesv** [comment]
:+1: Looks good to me. Nice one!

Non-essential extra: it'd be cool to add a check [here](https://github.com/jembi/openhim-bench/blob/master/openhim-bench.sh#L93) to check if perf is installed or not (I wasn't in my vagrant box).

**Comment by rcrichton** [comment]
@devcritter good idea. I assumed it would be as it part of the kernel tools but obviously not always there.

**Comment by rcrichton** [comment]
@devcritter I've added the check, mind looking it over again?

**Comment by hnnesv** [comment]
:+1:

**Comment by rcrichton** [comment]
Just for posterity, here is a dump of my notes for the other profiling options that I tried without success:
- nodetime fails to compile native
- look fails to compile nodetime native
- strongloop profiler freezes
- node-webkit-agent doesn't compile https://github.com/c4milo/node-webkit-agent/pull/79
- Devil doesn't start cos of undefined symbol
- v8-profiler is the same used in node-inspector
- dtrace4Linux doesn't work well for me - system freeze
- ltt-ng only works with io.js unless you implement your own probes

**Pull request merged**
